FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html
COPY spotify-logo.jpeg /usr/share/nginx/html/spotify-logo.jpeg
COPY Spotify_Logo_Green.png /usr/share/nginx/html/Spotify_Logo_Green.png
COPY Spotify_Primary_Logo_RGB_Black.ico /usr/share/nginx/html/Spotify_Primary_Logo_RGB_Black.ico

EXPOSE 80

